### ISSUE TITLE
Run w/o GPUs?

### ISSUE THREAD

**Issue by ghost** [eladhoffer/ImageNet-Training#16]
Hi,

Thanks for sharing the great work! I want run on it on my cheap Windows 7 desktop, which I plan to do with Cygwin. Will it break if I don't have the GPUs and set those flags to zero?

I have Windows 7, 32-bit, Core i5, 2.6 GHz, 4 GB RAM. Am I hopeless?

**Comment by eladhoffer** [comment]
Supposed to work without gpu (make sure to replace cudnn layers) but will be very sloooow
