### ISSUE TITLE
Out of Memory 

### ISSUE THREAD

**Issue by WenlinWang** [eladhoffer/ImageNet-Training#2]
I have tried the AlexNet 
th Main.lua -i 1 -b 128 -n AlexNet -r 0.01 -z adagrad

But got out of Memory error :  cuda runtime error : out of memory

my device is NVIDIA GTX TITAN which has 6GB memory, any ideas for the problem? (Even I change -b -32 still the same problem)

**Comment by eladhoffer** [comment]
I'll check it out. Are you using latest torch?

**Comment by WenlinWang** [comment]
Em, I have updated to the latest torch and changed to a K40 (12GB ram) but still something strange happened. 

-bash-4.1$ ls
Data.lua  ImageNetClasses  LICENSE  Main.lua  Models  README.md  ValidationLabels

-bash-4.1$ th Main.lua -i 1 -b 256 -n AlexNet -r 0.01 -z adagrad
==> processing options  
(DataProvider)===>Saving Batch  
(DataProvider)===>Generating filenames from path/project/myname/ILSVRC2014/ILSVRC2012_img_val/  
(DataProvider)===>Saving Batch  
Epoch 1 
nan 
Segmentation fault (core dumped)

I am not sure where goes wrong here. Any suggestions? (How do you set the path of your data files ?)

Mine is 
/ILSVRC2014/ILSVRC2012_img_train/ILSVRC2012_img_train.tar
/ILSVRC2014/ILSVRC2012_img_test/_.jpg  (huge number of images)
/ILSVRC2014/ILSVRC2012_img_val/_.jpg  (huge number of images)

Thanks so much for your sharing, 
- Wenlin

**Comment by eladhoffer** [comment]
Should be gone now, using LMDB for caching
