### ISSUE TITLE
Error when run CreatLMDBs.lua

### ISSUE THREAD

**Issue by jinyixin621** [eladhoffer/ImageNet-Training#4]
When I run CreatLMDBs.lua, I got:
/home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: /home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: ...xin/torch/install/share/lua/5.1/graphicsmagick/Image.lua:267: libGraphicsMagickWand.so: cannot open shared object file: No such file or directory

Can someone help with this?

**Comment by eladhoffer** [comment]
Install graphicsmagick lib:
sudo apt-get install libgraphicsmagick1-dev
