### ISSUE TITLE
How to install graphicsmagick

### ISSUE THREAD

**Issue by jinyixin621** [eladhoffer/ImageNet-Training#5]
Hello,
Somehow, I don't have apt-get in my terminal, so I just downloaded the graphicsmagick from their website. Also I use luarocks install graphicsmagick.Yet, I still got the same error.

/home/jinyixin/torch/install/bin/luajit: /home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: /home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: ...xin/torch/install/share/lua/5.1/graphicsmagick/Image.lua:267: libGraphicsMagickWand.so: cannot open shared object file: No such file or directory
stack traceback:
    [C]: in function 'error'
    /home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
    CreateLMDBs.lua:6: in main chunk
    [C]: in function 'dofile'
    ...ixin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406650

Please help me! Thank you very much.

**Comment by eladhoffer** [comment]
Check that you have the library in your LD_LIBRARY_PATH

**Comment by jinyixin621** [comment]
In my .bashrc

export PATH=/home/jinyixin/torch/pkg/gms/usr/local/bin:$PATH
export LD_LIBRARY_PATH=/home/jinyixin/torch/pkg/gms/usr/local/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=/home/jinyixin/torch/pkg/gms/usr/local/lib:$LIBRARY_PATH

Is that right?

**Comment by jinyixin621** [comment]
I cannot find file named libGraphicsMagickWand.so

under my directory /home/jinyixin/torch/pkg/gms/usr/local/lib there are GraphicsMagick-1.3.21  libGraphicsMagick++.a  libGraphicsMagick++.la   libGraphicsMagickWand.la
libGraphicsMagick.a    libGraphicsMagick.la   libGraphicsMagickWand.a  pkgconfig

**Comment by eladhoffer** [comment]
You can try to remove the graphicsmagick dependency by changing CreateLMDB.lua:
removing
"local gm = require 'graphicsmagick'"
and replacing
"local img = gm.Image(filename):toTensor('float','RGB','DHW')"
with
"local img = image.load(filename)"

**Comment by jinyixin621** [comment]
Thank you very much! I will try that.

**Comment by jinyixin621** [comment]
Hello, I figured out the issue with graphicsmagick, then I run th CreateLMDBs.lua, but it kind of stucks there. And I download the ILSVRC 2010 Imagenet dataset, is it ok?
stack traceback:
    [C]: in function 'concat'
    ...n/torch/install/share/lua/5.1/eladtools/DataProvider.lua:239: in function 'subdirs'
    ...n/torch/install/share/lua/5.1/eladtools/DataProvider.lua:293: in function '__init'
    /home/jinyixin/torch/install/share/lua/5.1/torch/init.lua:51: in function </home/jinyixin/torch/install/share/lua/5.1/torch/init.lua:47>
    [C]: in function 'FileSearcher'
    CreateLMDBs.lua:80: in main chunk
    [C]: in function 'dofile'
    ...ixin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406650
 Any help?

**Comment by jinyixin621** [comment]
Also get this error

[jinyixin@nyx7500 ImageNet-Training]$ th CreateLMDBs.lua 
(DataProvider)===>Saving Batch  
(DataProvider)===>Generating filenames from path/scratch/jiadeng_flux/jinyixin/data/ImageNet/validation1  
start  
/home/jinyixin/torch/install/bin/luajit: ...n/torch/install/share/lua/5.1/eladtools/DataProvider.lua:96: bad argument #1 to 'size' (dimension 1 out of range of 0D tensor at /home/jinyixin/torch/pkg/torch/generic/Tensor.c:17)
stack traceback:
    [C]: in function 'size'
    ...n/torch/install/share/lua/5.1/eladtools/DataProvider.lua:96: in function 'ShuffleItems'
    CreateLMDBs.lua:106: in main chunk
    [C]: in function 'dofile'
    ...ixin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406650

**Comment by clement-masson** [comment]
Hi jinyixin621.
Could you say more precisely how you figured out the issue with graphicsmagick ?
I am facing the very same problem.
Have installed GraphicsMagick (in fact, graphicsmagick, libgraphicsmagick3 and libgraphicsmagic++3) and luarocks install graphicsmagick.
I see the same error when requiring graphicsmagick and  I can't find the file "libGraphicsMagickWand.so" either ...

Where should I find the file CreateLMDB.lua to edit?

And when eladhoffer told "Check that you have the library in your LD_LIBRARY_PATH", was he talking about libGraphicsMagickWand.so ? 
Hwever, unlike you, I have no "gms" repertory in "/home/masson/torch/pkg" ...

Thanks for your help !

Clément

**Comment by jinyixin621** [comment]
Install linuxbrew(It is easy for installing some dependencies):
then run 
brew install graphicsmagick

Add the following to .bashrc(need modify the path)
export PATH=/home/jinyixin/.linuxbrew/Cellar/graphicsmagick/1.3.21/bin:$PATH
export LD_LIBRARY_PATH=/home/jinyixin/.linuxbrew/Cellar/graphicsmagick/1.3.21/lib:$LD_LIBRARY_PATH

**Comment by clement-masson** [comment]
Thanks ! I'll try that

**Comment by vnguyenKlick** [comment]
tried jinyixin621 comment on Jul 22, 2015 and it works:
setup: ubuntu 14 on aws p2 instance
