### ISSUE TITLE
Got this error for CreateLMDBs.lua

### ISSUE THREAD

**Issue by jinyixin621** [eladhoffer/ImageNet-Training#7]
th> require 'libjpeg'
/home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: ...jinyixin/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/home/jinyixin/torch/install/lib/lua/5.1/libjpeg.so':
    /home/jinyixin/torch/install/lib/lua/5.1/libjpeg.so: undefined symbol: jpeg_mem_dest
stack traceback:
    [C]: in function 'error'
    /home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
    [string "_RESULT={require 'libjpeg'}"]:1: in main chunk
    [C]: in function 'xpcall'
    /home/jinyixin/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
    ...ixin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
    [C]: at 0x00405800  

Any help?

**Comment by eladhoffer** [comment]
sudo apt-get install libjpeg8-dev

**Comment by jinyixin621** [comment]
Also I got Error in LMDB function mdb_cursor_get :  MDB_NOTFOUND: No matching key/data pair found. What was wrong with this?

**Comment by eladhoffer** [comment]
It's ok, the LMDB was empty on start so you got this error
